name: Daily LLM API Test

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./llm-web-api
        run: npm install

      - name: Run API LLM Test Script
        working-directory: ./llm-web-api
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          chmod +x ./test_llm.sh
          ./test_llm.sh

      - name: Run Redis Test Script
        working-directory: ./llm-web-api
        env:
          UPSTASH_REDIS_REST_URL: "https://eternal-antelope-106176.upstash.io"
          UPSTASH_REDIS_REST_TOKEN: "gQAAAAAAAZ7AAAIgcDE5YTlkNmFhMzQ3MzI0YjZkOGE0NDRmNWEzMTc4M2RiMw"
        run: npx tsx test-redis.ts

