name: Daily LLM API Test

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./llm-web-api
        run: npm install

      - name: Run API LLM Test Script
        working-directory: ./llm-web-api
        run: node test_llm.mjs

      - name: Run Redis Test Script
        working-directory: ./llm-web-api
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
        run: npx ts-node test-redis.ts
